import { DashboardNav, MiniNavbar, Navbar } from "@/components";

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <div className='min-h-screen min-w-screen bg-cardPrimary'>
         <MiniNavbar />
         <Navbar />
         <div className='container mx-auto flex flex-col gap-5'>
            <DashboardNav />
            {children}
         </div>
      </div>
   );
}
